// cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const EA_CHANGE = 'EA_CHANGE'


// product
export const PRODUCTS_LOAD = 'PRODUCTS_LOAD'
export const PRODUCTS_REQUEST_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS'
export const PRODUCTS_REQUEST_FAIL = 'PRODUCTS_REQUEST_FAIL'

export const PRODUCT_LOAD = 'PRODUCT_LOAD'
export const PRODUCT_REQUEST_SUCCESS = 'PRODUCT_REQUEST_SUCCESS'
export const PRODUCT_REQUEST_FAIL = 'PRODUCT_REQUEST_FAIL'

export const REVIEW_ADD = 'REVIEW_ADD'
export const REVIEW_DELETE = 'REVIEW_DELETE'


// order
export const ORDER_ADD = 'ORDER_ADD'
export const ORDER_DELETE = 'ORDER_DELETE'
export const ORDER_PROCESS = 'ORDER_PROCESS'


// common
export const LOAD_NEW_PAGE = 'LOAD_NEW_PAGE'

